# Dependabot Configuration - Halterofit
# Industry Standard: Selective Automation with Semver Rules
# Philosophy: Auto-merge safe updates, manual review for breaking changes

version: 2
updates:
  # NPM Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"

    # Limit concurrent PRs to avoid overwhelming
    open-pull-requests-limit: 5

    # Group similar updates to reduce PR noise
    groups:
      # Dev dependencies - Auto-merged by CI workflow
      # TypeScript, ESLint, Jest, Prettier, etc.
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "lint-staged"
          - "husky"
          - "@commitlint/*"
          - "jest*"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"

      # Runtime patch updates - Auto-merged by CI workflow
      # Bug fixes only (0.0.X), low risk
      runtime-patches:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "lint-staged"
          - "husky"
          - "@commitlint/*"
          - "jest*"
          - "@testing-library/*"
        update-types:
          - "patch"

    # Critical packages always get separate PRs (easier to review)
    # Expo, React, React Native, WatermelonDB, Supabase
    # Minor/major updates require manual review

    commit-message:
      prefix: "chore(deps)"

  # GitHub Actions - Auto-merged after CI passes
  # SHA pinning ensures security
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"

    open-pull-requests-limit: 3

    commit-message:
      prefix: "chore(ci)"
