name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Cancel in-progress runs when a new commit is pushed to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Least privilege permissions
permissions:
  contents: read

jobs:
  test:
    name: Test (Type-Check, Lint, Unit Tests)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        # SHA pinning for security: immutable reference + version comment for readability
        # Dependabot will automatically update both SHA and comment
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.3.0
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type-check
        run: npm run type-check

      - name: ESLint
        run: npm run lint

      - name: Run tests
        run: npm test -- --ci --coverage --maxWorkers=2

      - name: Upload coverage reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30
