name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Cancel in-progress runs when a new commit is pushed to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default permissions (read-only)
permissions:
  contents: read

jobs:
  test:
    name: Test (Type-Check, Lint, Unit Tests)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        # SHA pinning for security: immutable reference + version comment for readability
        # Dependabot will automatically update both SHA and comment
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type-check
        run: npm run type-check

      - name: ESLint
        run: npm run lint

      - name: Run tests
        run: npm test -- --ci --coverage --maxWorkers=2

      - name: Upload coverage reports
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4.6.0
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

  # Dependabot Auto-Merge (Industry Standard Pattern)
  # Automatically merges Dependabot PRs after CI passes
  # Only merges: dev dependencies + patch updates for runtime
  dependabot:
    name: Dependabot Auto-Merge
    needs: [test]
    runs-on: ubuntu-latest

    # Only run on Dependabot PRs
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'

    # Elevated permissions for merging
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge GitHub Actions
        # GitHub Actions: CI infrastructure, not app code
        # Industry standard: Auto-merge all versions after CI passes
        # NOTE: fetch-metadata returns 'github_actions' not 'github-actions'
        if: steps.metadata.outputs.package-ecosystem == 'github_actions'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge dev dependencies
        # Dev dependencies: ESLint, TypeScript, Jest, etc.
        # Safe to auto-merge minor/patch, manual review for major
        if: |
          steps.metadata.outputs.dependency-type == 'direct:development' &&
          steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge runtime patch and minor updates
        # Runtime patch (0.0.X): Bug fixes only
        # Runtime minor (0.X.0): New features, backward compatible (semver promise)
        # Industry standard: Auto-merge both after CI passes
        # Example: react-native 0.73.1 -> 0.73.2 (patch) or 0.73.0 -> 0.74.0 (minor)
        if: |
          steps.metadata.outputs.dependency-type == 'direct:production' &&
          (steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
           steps.metadata.outputs.update-type == 'version-update:semver-minor')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on MAJOR updates requiring review
        # Major updates (X.0.0): Breaking changes - ALWAYS require manual review
        # Post helpful comment with action items
        if: |
          steps.metadata.outputs.dependency-type == 'direct:production' &&
          steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment "$PR_URL" --body "🚨 **MAJOR UPDATE - Breaking Changes Expected**

          This is a ${{ steps.metadata.outputs.update-type }} update for a runtime dependency.

          **Required actions before merging:**
          1. Read the changelog and migration guide
          2. Review all breaking changes
          3. Test the app thoroughly on both iOS and Android
          4. Check for required code changes

          ⚠️ Do NOT auto-merge this PR without careful review!"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
