name: Dependabot Auto-Merge

on:
  # Trigger after CI completes
  workflow_run:
    workflows: ["CI"]
    types: [completed]

# Least privilege permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge dev dependencies
    runs-on: ubuntu-latest
    # Only run if CI succeeded and PR is from Dependabot
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.actor == 'dependabot[bot]'

    steps:
      - name: Get PR number
        id: pr
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --head dependabot/${{ github.event.workflow_run.head_branch }} --json number --jq '.[0].number')
          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Dependabot metadata
        id: metadata
        # SHA pinning for security: immutable reference + version comment for readability
        # Dependabot will automatically update both SHA and comment
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge dev dependencies
        if: steps.metadata.outputs.dependency-type == 'direct:development'
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ steps.pr.outputs.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
